version: '3'
services:
  eureka-server:
    image: eureka-server:1.0
    container_name: eureka-server
    expose:
      - "8761"
    ports:
      - 8761:8761
  diagnostic-service:
    image: diagnostic-service:1.0
    #container_name: owner-service
    ports:
      - 8180:8180
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://eureka-server:8761/eureka  -DDB_USER=root -DDB_PASSWORD=root -DJDBC=jdbc:mariadb://localhost:3306/clinicmanagement_diagnosticservice_db

    links:
      - eureka-server
  doctor-service:
    image: vet-service:1.0
    #container_name: vet-service
    ports:
      - 8280:8280
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://eureka-server:8761/eureka  -DDB_USER=root -DDB_PASSWORD=root -DJDBC=jdbc:mariadb://localhost:3306/clinicmanagement_doctorservice_db

    links:
      - eureka-server
  patient-service:
    image: patient-service:1.0
    #container_name: visit-service
    ports:
      - 8380:8380
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://eureka-server:8761/eureka  -DDB_USER=root -DDB_PASSWORD=root -DJDBC=jdbc:mariadb://localhost:3306/clinicmanagement_patientservice_db

    links:
      - eureka-server
  api-gateway:
    image: api-gateway:1.0
    #container_name: apigateway-service
    ports:
      - "8480:8480"
    environment:
      - JAVA_OPTS= -DEUREKA_SERVER=http://eureka-server:8761/eureka #(name of eureka host==eureka container name)

    links:
      - eureka-server
